# list of available linters - https://golangci-lint.run/usage/linters/

# Copyright (c) 2024 Falcon V Systems S.A.
# No portions of this software may be used, reproduced, derived from
# or distributed without express permission of Falcon V Systems S.A.
run:
  timeout: 3m
  allow-parallel-runners: true

# output configuration options
output:
  formats:
    - format: colored-line-number
      path: stdout
  sort-results: true

linters:
  enable:
    - dupl
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - makezero
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - whitespace
    - depguard
    - goheader
    - funlen
    - gosec
    - gofumpt
    - gci
    - unused
    - errcheck
    - wrapcheck
  disable: # disabled due to lack of support for go@1.18
    # ----------------
    - gomnd
linters-settings:
  gosec:
    excludes:
      - G115 # disabled due to lack of support in freeconf (Potential integer overflow when converting between integer types)
  depguard:
    rules:
      main:
        files:
          - "$all"
        allow:
          - $gostd
          - github.com/
          - code.falcon.lab/
          - k8s.io/
        deny:
          - pkg: "github.com/go-playground/assert/v2"
            desc: "Please, use github.com/stretchr/testify instead"
          - pkg: "github.com/golang/mock"
            desc: "No longer maintained, please, use go.uber.org/mock instead"
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  tagliatelle:
    case:
      rules:
        json: goCamel
        yaml: goCamel

  goheader:
    values:
      regexp:
        creation_year: ^\d{4}
    template: |-
        Author: Maciej Tonderski

  revive:
    rules:
      - name: "var-naming"
        # In Go, the convention is to use camel case also for phrases which
        # usually are written in all-caps (someHttp and not someHTTP). Some
        # linters however decided that it's fine to capitalize some of the
        # words. The phrase "MAC-NE ID" is all-caps, and there's no reason to
        # make "ID" stand out, so we add "ID" to blacklist here to disable
        # that.
        arguments: [["ID", "JSON", "URI", "HTTP", "UUID", "RPC", "URL", "IP"], []]

  stylecheck:
    # Same as above.
    initialisms: [""]


issues:
  exclude-rules:
    # Disable linters for tests CT
    - path: 'tests/(.+)_test\.go'
      linters:
        - dupl
    - path: '(.+)_test\.go'
      linters:
        - errcheck
        - funlen
        - dupl
    # Disable linter for autogenerated RCP defintions
    - path: '(.+)/rcpdefs\.go'
      linters:
        - revive
        - unused
